name: ltcva
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip=22.3
  - pytorch=2.3.0
  - torchvision
  - numpy=1.24.3
  - pandas=2.0.1
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - pyyaml=6.0
  - tqdm=4.65.0
  - tensorboard=2.13.0
  - jupyterlab=4.0.0
  - pip:
    - ipywidgets==8.0.6 